# LIT Bytes cards worker.
kv_namespaces = [
  { binding = "LIT_STATS", id = "30690d02e4a44938950c08724e84b066" }
]

name = "lit-bytes-cards"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]

[[rules]]
type = "Data"
globs = ["**/*.woff"]
